### ISSUE TITLE
Not working well and asking for help

### ISSUE THREAD

**Issue by Byter432** [Gertje823/Videoland-Sub-Downloader#1]
For movies it's working (VTT file but no problem with that) but not for series. Maybe you can help:

G:\python Videoland-Sub-Downloader.py
Wat is de Videoland url?https://www.videoland.com/series/500503/temptation-island-love-or-leave
Welk seizoen? (bv. 3)1
Traceback (most recent call last):
  File "G:\Videoland-Sub-Downloader.py", line 57, in <module>
    for season in data["videos"]["details"]["S500175"]["refs"]:
KeyError: 'S500175'

G:\python Videoland-Sub-Downloader.py
Wat is de Videoland url?https://www.videoland.com/films/25800/hartenstraat
2014
Hartenstraat.(2014).vtt aan het downloaden
Converting to srt
Traceback (most recent call last):
  File "G:\Videoland-Sub-Downloader.py", line 32, in <module>
    vtt_to_srt(filename)
TypeError: 'module' object is not callable

**Comment by Gertje823** [comment]
Updated the script, should be working now.

**Comment by Byter432** [comment]
Working perfect now. 
Thanks
