### ISSUE TITLE
requests issue

### ISSUE THREAD

**Issue by ghost** [Gertje823/Videoland-Sub-Downloader#2]
Traceback (most recent call last):
  File "C:\Users\M\Downloads\Videoland-Sub-Downloader-master\Videoland-Sub-Downloader-master\Videoland-Sub-Downloader.py", line 1, in <module>
    import requests, re, json, time, os
ModuleNotFoundError: No module named 'requests'

isnt working , getting this error

**Comment by Gertje823** [comment]
You need to install the `requests` python module. Just run `pip install -r requirements.txt` to install all the needed modules.

**Comment by ghost** [comment]
lol, im happy just running a python window...where do i run this command?
it says invalid syntax when i run this in python window and says pip is an invalid command with cmd

**Comment by bertocus** [comment]
`pip install -r requirements.txt` needs to be run from a Windows command prompt. Search for `cmd` in Windows to open one.
In the CMD window, enter `cd C:\Users\M\Downloads\Videoland-Sub-Downloader-master\Videoland-Sub-Downloader-master\` to navigate to the folder where the requirements.txt file is located.
Then run the pip install command listed above.

Edit: just saw your edit. This means Python isn't in your PATH.
https://geek-university.com/python/add-python-to-the-windows-path/

**Comment by ghost** [comment]
thanks it worked somehow, however, now that i tried it on a random serie, its not working, just freezing.
= RESTART: C:\Users\M\Downloads\Videoland-Sub-Downloader-master\Videoland-Sub-Downloader.py
Wat is de Videoland url?https://www.videoland.com/series/500591/american-housewife
Welk seizoen? (bv. 3)3
>>> 
only showing >>> nothing else.

**Comment by bertocus** [comment]
I can reproduce that, it does the same for me on that specific URL. @Gertje823 will fix it.

**Comment by ghost** [comment]
ok thanks. how would i know if subtitles are available, because everytime i use it, there simply isnt any subtitle found???

i had the same issue on: https://www.videoland.com/series/1434/temptation-island-usa endless loading with >>>

**Comment by ghost** [comment]
i saw an update, however the new .py file doesn't have the cookie field..

**Comment by Gertje823** [comment]
@dabtapp Could you try it with the new python file? It should be working now.

**Comment by ghost** [comment]
> 
> 
> @dabtapp Could you try it with the new python file? It should be working now.

tried, there is no cookie field in the new file.

**Comment by Gertje823** [comment]
Check the new file i just added 14 minutes ago.

**Comment by bertocus** [comment]
Thanks you @Gertje823. it is working perfectly now. You are a good programmer!!! 😀 Keep up the good work. I am looking forward to your next project.

**Comment by ghost** [comment]
lol, Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering
Sorry, er is geen ondertiteling gevonden voor deze aflevering

guess that works...

**Comment by Gertje823** [comment]
Not all episodes on videoland have separated subtitle files. As stated in the readme: _Het kan zijn dat er voor bepaalde series geen ondertiteling te downloaden is omdat deze is 'ingebakken' in het videobestand zelf._

**Comment by ghost** [comment]
> 
> 
> Not all episodes on videoland have separated subtitle files. As stated in the readme: _Het kan zijn dat er voor bepaalde series geen ondertiteling te downloaden is omdat deze is 'ingebakken' in het videobestand zelf._

unfortunately i encounter it with every movie and serie i tried. And i tried ten-twenty of them.

**Comment by Gertje823** [comment]
> 
> unfortunately i encounter it with every movie and serie i tried. And i tried ten-twenty of them.

https://www.videoland.com/series/500503/temptation-island-love-or-leave and https://www.videoland.com/series/500175/h-3-l/3033 work just fine. I think they only have separate subs for dutch content.
