### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by Byter432** [Gertje823/Videoland-Sub-Downloader#3]
Can you check this:
I can download:
https://www.videoland.com/series/500503/temptation-island-love-or-leave/4367

and this one is not working:
https://www.videoland.com/series/1067/expeditie-robinson/4371

(using the same cookie for both)

thnx in advance

**Comment by Gertje823** [comment]
Should be fixed now 😉

**Comment by Byter432** [comment]
It doesn't ask for an url but gives an error:

C:\Videoland>python videoland-sub-downloader.py
  File "C:\Videoland\videoland-sub-downloader.py", line 57
    for item in data["videos"]["details"]:
IndentationError: expected an indented block

**Comment by Gertje823** [comment]
Oops.. 
It is working for me now. Could you try again?

**Comment by Byter432** [comment]
Everything working perfect now. Thanks!!!!
