### ISSUE TITLE
Error in line 84

### ISSUE THREAD

**Issue by alnaito** [Gertje823/Videoland-Sub-Downloader#4]
Thanks a lot for writing this script.

I ran into the following error while running it:
`Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\Videoland-Sub-Downloader.py", line 84, in <module>
    open(filename, 'wb').write(r.content)
OSError: [Errno 22] Invalid argument: 'Are.You.The.One?.De.Perfecte.Match.S01E01.vtt'`
This error occurs when trying to select Are You The One? season 1.

I tried two other different series, for which it worked fine. So it only happens for "Are You The One?".

Maybe it's due to the question mark in the title?
Could you please have a look? Thanks!

**Comment by Gertje823** [comment]
Thanks for creating this issue! It was indeed due to an invalid character in the file name. Now the invalid characters will be escaped. 😉
